// Code generated by go-swagger; DO NOT EDIT.
// Copyright 2017-2020 Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

// Package server Cilium Operator
//
//  Cilium
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /v1beta
//  Version: v1beta
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
